version: "3.7"
services:
  ## POSTGRES ##
  postgres_db:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=demo
    restart: always
    volumes:
      - ./server/database/data/dev:/var/lib/postgresql/data
    container_name: postgres_db
    ports:
      - 5432:5432
  ## SERVER ##
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    container_name: nest-docker-postgres
    ports:
      - "5500:5500"
    depends_on:
      - postgres_db
    volumes:
      - ./server/src:/app/src

  ## CLIENT ##
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./client/.env
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
    ports:
      - 3333:3333
    restart: always
    container_name: nest-docker-client

  ## PG ADMIN ##
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - postgres_db
